version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  parser:
    build: ./parser
    container_name: parser
    ports:
      - '5001:5001'
  
  server:
    build: ./server
    container_name: server
    ports:
      - '5000:5000'
    env_file:
      - ./server/.env
    depends_on:
      - mongo
      - parser
